Repository PizzaPickle/Frontend, pull requests merged in 2024-08, with the labels that each got.

#5 feat: header 컴포넌트 구현
  pickle-frontend/package-lock.json
  pickle-frontend/package.json
  pickle-frontend/public/assets/alarm.svg
  pickle-frontend/public/assets/pickle.svg
  pickle-frontend/public/assets/sun.svg
  pickle-frontend/src/App.jsx
  pickle-frontend/src/components/common/header/Header.jsx
  pickle-frontend/src/components/common/header/Header.style.js
  pickle-frontend/src/index.css
  pickle-frontend/src/main-router.jsx
  pickle-frontend/src/routes/test/TestPage.jsx
  pickle-frontend/src/theme.js
Labels: ✨ Feature

#11 feat: side-bar 구현
  pickle-frontend/public/assets/side-home.svg
  pickle-frontend/public/assets/side-mydata.svg
  pickle-frontend/public/assets/side-pb.svg
  pickle-frontend/public/assets/side-port.svg
  pickle-frontend/public/assets/side-room.svg
  pickle-frontend/src/components/common/header/Header.style.js
  pickle-frontend/src/components/common/sidebar/Sidebar.jsx
  pickle-frontend/src/components/common/sidebar/Sidebar.style.js
  pickle-frontend/src/index.css
  pickle-frontend/src/theme.js
Labels: ✨ Feature

#14 Feature/common component walletcard
  pickle-frontend/public/assets/mydata-locking.svg
  pickle-frontend/public/assets/mywallet.png
  pickle-frontend/src/components/common/mydata/badge/Badge.jsx
  pickle-frontend/src/components/common/mydata/badge/Badge.style.js
  pickle-frontend/src/components/common/sidebar/Sidebar.style.js
  pickle-frontend/src/components/common/wallet-card/WalletCard.jsx
  pickle-frontend/src/components/common/wallet-card/WalletCard.style.js
  pickle-frontend/src/index.css
  pickle-frontend/src/routes/test/TestPage.jsx
Labels: ✨ Feature

#15 fix: props width height 받기 추가
  pickle-frontend/src/components/common/wallet-card/WalletCard.jsx
  pickle-frontend/src/routes/test/TestPage.jsx
Labels: 🐛 fix

#16 feat: 고객 대기 상담룸 목록 페이지 내 상담 목록 카드 구현하였습니다.
  pickle-frontend/public/assets/MapPin.svg
  pickle-frontend/public/assets/PBimg.svg
  pickle-frontend/public/assets/bell.svg
  pickle-frontend/src/components/common/customer-consulting-room/ ConsultingRoom.jsx
  pickle-frontend/src/components/common/customer-consulting-room/ConsultingRoom.style.js
Labels: ✨ Feature

#17 feat: 고객 요청서 목록 카드 구현
  pickle-frontend/src/components/common/customer-requset-list/RequestList.jsx
  pickle-frontend/src/components/common/customer-requset-list/RequestList.style.js
Labels: ✨ Feature

#18 feat: StrategyBox 컴포넌트 구현
  pickle-frontend/src/components/common/circular-graph/CircularGraph.jsx
  pickle-frontend/src/components/common/circular-graph/CircularGraph.style.js
  pickle-frontend/src/components/common/graph-width-legend/LegendWithGraph.jsx
  pickle-frontend/src/components/common/graph-width-legend/LegendWithGraph.style.js
  pickle-frontend/src/components/common/legend/Legend.jsx
  pickle-frontend/src/components/common/legend/legend.style.js
  pickle-frontend/src/components/common/stock-table/ProgressBar.jsx
  pickle-frontend/src/components/common/stock-table/StockTable.jsx
  pickle-frontend/src/components/common/stock-table/prgressBar.style.js
  pickle-frontend/src/components/common/stock-table/stockTable.style.js
  pickle-frontend/src/components/common/strategy/box/StrategyBox.jsx
  pickle-frontend/src/components/common/strategy/box/StrategyBox.style.js
  pickle-frontend/src/main.jsx
  pickle-frontend/src/routes/test/TestPage.jsx
  pickle-frontend/src/theme.js
Labels: ✨ Feature

#20 feat: 고객 홈화면 UI 구현 완료
  pickle-frontend/public/assets/home-bell.svg
  pickle-frontend/public/assets/home-next.svg
  pickle-frontend/public/assets/home-pb1.svg
  pickle-frontend/public/assets/home-pb2.svg
  pickle-frontend/public/assets/home-pb3.svg
  pickle-frontend/public/assets/stockUp.svg
  pickle-frontend/src/components/common/header/Header.style.js
  pickle-frontend/src/components/common/mydata/allmoney/AllMoney.jsx
  pickle-frontend/src/components/common/mydata/allmoney/AllMoney.style.js
  pickle-frontend/src/components/common/mydata/allmoney/AllMoneyEx.jsx
  pickle-frontend/src/components/common/sidebar/Sidebar.style.js
  pickle-frontend/src/components/common/wallet-card/WalletCard.jsx
  pickle-frontend/src/components/customer-home/profit-card/ProfitCard.jsx
  pickle-frontend/src/components/customer-home/profit-card/ProfitCard.style.js
  pickle-frontend/src/main-router.jsx
  pickle-frontend/src/pages/Homepage/HomePage.jsx
  pickle-frontend/src/pages/Homepage/HomePage.style.js
  pickle-frontend/src/routes/test/TestPage.jsx
  pickle-frontend/src/theme.js
Labels: ✨ Feature, 📖 story
